apiVersion: v1
kind: ReplicationController
metadata: 
  name: javawebapprc 
  namespace: test-ns
spec:
  replicas: 2
  selector:
    app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels: 
        app: javawebapp
    spec: 
      containers:
      - name: javawebappcontainer
        image: dockernaveen04/java-web-app-docker:32
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
   name: javawebappsvc
   namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 80
    name: nginx
  - port: 8080
    targetPort: 8080
    name: tomcat 

